sudo: required

services:
- docker

cache:
  directories:
  - "$HOME/.cache"

language: C

env:
  matrix:
  - OS=debian DIST=bullseye
  - OS=debian DIST=buster
  - OS=debian DIST=stretch
  - OS=debian DIST=jessie
  - OS=debian DIST=wheezy
  - OS=ubuntu DIST=jammy
  - OS=ubuntu DIST=focal
  - OS=ubuntu DIST=bionic
  - OS=ubuntu DIST=xenial
  - OS=ubuntu DIST=trusty
  - OS=ubuntu DIST=precise
  - OS=el DIST=8
  - OS=el DIST=7
  - OS=el DIST=6
  - OS=fedora DIST=33
  - OS=fedora DIST=32
  - OS=fedora DIST=31
  - OS=fedora DIST=30
  - OS=fedora DIST=29
  - OS=fedora DIST=28
  - OS=fedora DIST=27
  - OS=fedora DIST=26
  - OS=fedora DIST=25
  - OS=fedora DIST=24
  - OS=debian DIST=bullseye ARCH=i386
  - OS=debian DIST=buster ARCH=i386
  - OS=debian DIST=stretch ARCH=i386
  - OS=debian DIST=jessie ARCH=i386
  - OS=debian DIST=wheezy ARCH=i386
  - OS=ubuntu DIST=jammy ARCH=i386
  - OS=ubuntu DIST=focal ARCH=i386
  - OS=ubuntu DIST=bionic ARCH=i386
  - OS=ubuntu DIST=xenial ARCH=i386
  - OS=ubuntu DIST=trusty ARCH=i386
  - OS=ubuntu DIST=precise ARCH=i386

git:
  depth: false

jobs:
  allow_failures:
  - env: OS=debian DIST=jessie ARCH=i386

script:
- git describe --long
- git clone https://github.com/packpack/packpack.git packpack
- packpack/packpack
deploy:
  provider: releases
  api_key:
    secure: kA35Q0IH/31+GCMGdOk8Y0SXIln3R+zCCA7aL1Vcie3203+9QNBwTqLxI9IF62Ebj4MjhwygbHLJCrtK62yDTeUoB/Ms73wINNpEAK5ZOHHbee3/o9d/nzYd3AjGgp8OlCzOE5zleMOYGYS+gN4qJWMxqAzJzlhJL4Uun0HJfI5TTKlpLwU/qiKX5NSI+k60oTfRfPC8vbyCqoeyurLuoyCxXmE+TEMbfeBHq83B3ZLNKd/XTLUlE3W2cKhkxTg0841R6Qbi9vXsH7U5mkyXe1dfhOPPOPFlNvUsxKgVzNQcAdDPWrVJda4eUkFPcURGKvhUvzC1ucMGrnOoPazV9xZabf+23Ozcrr51uB4L1iw0qbGGlGtTmWElKS/kWiBB2ui/9TqVDvwVSZ4DJnFwELIOvt/AvgG/9qbKiHY0eZHRXVCJvQUVpS8W+WYdHEBqCeAJazeYnjzJOIonXUDbN+OLunHImrFjJzPgtOwYUBnurUTcHsAtARTLfLFDIuHPreTOhpjVpEaUfgQzi/1G6mGfhhFAX6fm7hevoabm0pRXqAyhpkAIDHEBmB3vUQkr2G2NBhSZWGeENIM6jn0DHTGX6ILwrQzTrxJrAjJq/iIMQhSvxTNQJ7tsjYb5YgXntk7y5PICT5TmJNSqoNko01dU4uIs/bMC78jbwBajP6Y=
  file_glob: true
  file: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    tags: true
    repo: matricali/cbrutekrag
