name: Windows CMake Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgCommitId: 'latest'
          runVcpkgInstall: true

      - name: Configure with CMake
        run: |
          cmake --preset default

      - name: Build with CMake
        run: |
          cmake --build build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cbrutekrag-w64
          path: |
            build/src/cbrutekrag.exe
            build/src/libcrypto-3-x64.dll
            build/src/pthreadVC3.dll
            build/src/ssh.dll
